# Generated by Django 3.0.1 on 2020-06-17 10:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parent_name', models.CharField(default='', max_length=200)),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('phone', models.TextField(blank=True, default='7123123', max_length=500)),
                ('parent_phone', models.TextField(blank=True, default='712312', max_length=500)),
                ('email', models.EmailField(default='', max_length=254)),
                ('parent_email', models.EmailField(default='', max_length=254)),
                ('city', models.CharField(default='', max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('reward_card_amount', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('image', models.ImageField(blank=True, default='', upload_to='images')),
                ('signup_confirmation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.TextField(blank=True, default='79151761287', max_length=500)),
                ('email', models.EmailField(default='', max_length=254)),
                ('city', models.CharField(default='', max_length=60)),
                ('currency', models.CharField(choices=[('RUB', 'Ruble'), ('USD', 'Dollar'), ('EUR', 'Euro')], default='RUB', max_length=3)),
                ('salary_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('salary_rate_time_interval', models.DurationField(blank=True, default=datetime.timedelta(seconds=3600))),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.TeacherStatus')),
                ('students', models.ManyToManyField(blank=True, related_name='teachers', to='students.Student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRewardCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('deleted', models.BooleanField(default=False)),
                ('lesson_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_cards', to='courses.LessonRoom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_cards', to='students.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_reward_cards', to='students.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.StudentStatus'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
