# Generated by Django 3.0.6 on 2020-05-19 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentstatus',
            old_name='name',
            new_name='name_status',
        ),
    ]
