# Generated by Django 3.0.1 on 2020-06-18 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_manager_email'),
        ('students', '0002_teacher_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supervised_teachers', to='managers.Manager'),
            preserve_default=False,
        ),
    ]
