# Generated by Django 3.0.1 on 2020-04-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.TextField(blank=True, default='712312', max_length=500),
        ),
    ]
