# Generated by Django 3.0.1 on 2020-06-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_teacher_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_level',
            field=models.CharField(choices=[('BG', 'Beginner'), ('MD', 'Middle'), ('AD', 'Advanced')], default='BG', max_length=2),
        ),
    ]
