# Generated by Django 3.0.1 on 2020-05-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20200527_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
