# Generated by Django 3.0.1 on 2020-05-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_schedule_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='comment',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
