# Generated by Django 3.0.1 on 2020-06-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_responsible_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='communication',
            field=models.CharField(default='', max_length=250),
        ),
    ]
