# Generated by Django 3.0.1 on 2020-04-08 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20200405_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('assign_task', 'Assign task'),)},
        ),
    ]
