# Generated by Django 3.0.1 on 2020-06-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_communication'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(default='', max_length=250),
        ),
    ]
