# Generated by Django 3.0.1 on 2020-05-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20200527_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='students.Student'),
        ),
    ]
