# Generated by Django 3.0.1 on 2020-06-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.CharField(default='', max_length=3),
        ),
    ]
