# Generated by Django 3.0.1 on 2020-04-19 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20200419_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='students.StudentStatus'),
        ),
    ]
