# Generated by Django 3.0.1 on 2020-05-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20200528_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
