# Generated by Django 3.0.1 on 2020-04-19 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20200419_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentstatus',
            options={'verbose_name': 'Student statuses'},
        ),
    ]
