# Generated by Django 3.0.1 on 2020-06-01 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRewardCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('deleted', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_cards', to='students.Student')),
            ],
        ),
    ]
