# Generated by Django 3.0.1 on 2020-04-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20200419_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('amount', models.FloatField(default=0.0)),
                ('lessons', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Student subscription',
            },
        ),
        migrations.AlterModelOptions(
            name='studentstatus',
            options={'verbose_name': 'Student status', 'verbose_name_plural': 'Student statuses'},
        ),
    ]
