# Generated by Django 3.0.1 on 2020-06-02 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_image'),
        ('students', '0010_studentrewardcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrewardcard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_cards_old', to='students.Student'),
        ),
        migrations.CreateModel(
            name='StudentRewardCardModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('deleted', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_cards', to='courses.Module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_cards', to='students.Student')),
            ],
        ),
    ]
