# Generated by Django 3.0.1 on 2020-06-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_student_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
