# Generated by Django 3.0.1 on 2020-06-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20200602_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentRewardCard',
        ),
    ]
