# Generated by Django 3.0.1 on 2020-04-19 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20200419_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentstatus',
            options={'verbose_name_plural': 'Student statuses'},
        ),
    ]
