# Generated by Django 3.0.1 on 2020-06-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_course_image'),
        ('students', '0012_delete_studentrewardcard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentRewardCardModels',
            new_name='StudentRewardCard',
        ),
    ]
