# Generated by Django 3.0.1 on 2020-06-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_remove_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='PFDO_certificate',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
