# Generated by Django 3.0.1 on 2020-04-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20200419_2111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentSubscription',
        ),
        migrations.DeleteModel(
            name='StudentTask',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='student',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
    ]
