# Generated by Django 3.0.1 on 2020-06-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_student_pfdo_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='next_contact',
            field=models.CharField(default='', max_length=250),
        ),
    ]
