# Generated by Django 3.0.1 on 2020-06-02 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20200602_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrewardcard',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='set_reward_cards', to='students.Teacher'),
            preserve_default=False,
        ),
    ]
