# Generated by Django 3.0.1 on 2020-04-19 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20200419_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='amount',
        ),
    ]
