# Generated by Django 3.0.1 on 2020-06-03 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lessonroom_schedule'),
        ('students', '0014_studentrewardcard_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrewardcard',
            name='module',
        ),
        migrations.AddField(
            model_name='studentrewardcard',
            name='lesson_room',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='reward_cards', to='courses.LessonRoom'),
            preserve_default=False,
        ),
    ]
