# Generated by Django 3.0.1 on 2020-04-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_remove_student_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
