# Generated by Django 3.0.1 on 2020-06-29 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_funnelstage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funnelstage',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='funnel_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.FunnelStage'),
        ),
    ]
