# Generated by Django 3.0.1 on 2020-06-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_auto_20200603_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reward_card_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
