# Generated by Django 3.0.1 on 2020-06-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20200629_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='communication',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='next_contact',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_class',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
