# Generated by Django 3.0.1 on 2020-04-19 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_student_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='amount',
        ),
    ]
