# Generated by Django 3.0.1 on 2020-06-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_student_reward_card_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
