# Generated by Django 3.0.1 on 2020-06-16 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_auto_20200616_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Ruble'), ('USD', 'Dollar'), ('EUR', 'Euro')], default='RUB', max_length=3),
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary_rate_duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=3600)),
        ),
    ]
