# Generated by Django 3.0.1 on 2020-04-19 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_studentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.ForeignKey(default='Lead', on_delete=django.db.models.deletion.CASCADE, to='students.StudentStatus'),
        ),
    ]
