# Generated by Django 3.0.1 on 2020-04-19 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_student_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
    ]
