# Generated by Django 3.0.1 on 2020-04-19 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0021_remove_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.StudentStatus'),
        ),
    ]
