# Generated by Django 3.0.1 on 2020-04-21 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0023_student_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.TextField(blank=True, default='79151761287', max_length=500)),
                ('city', models.CharField(default='', max_length=60)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.TeacherStatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
