# Generated by Django 3.0.1 on 2020-05-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_teacher_teacherstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='patronymic',
            field=models.CharField(default='', max_length=200),
        ),
    ]
