# Generated by Django 3.0.1 on 2020-05-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_auto_20200505_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='signup_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
