# Generated by Django 3.0.1 on 2020-05-05 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_student_signup_confirmation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='patronymic',
        ),
    ]
