# Generated by Django 3.0.1 on 2020-05-11 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_teacherschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherschedule',
            old_name='owner',
            new_name='teacher',
        ),
    ]
