# Generated by Django 3.0.1 on 2020-05-12 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0031_auto_20200511_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherschedule',
            name='parent_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='teacherschedule',
            name='phone',
            field=models.TextField(blank=True, default='79151761287', max_length=500),
        ),
        migrations.AddField(
            model_name='teacherschedule',
            name='student_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
