# Generated by Django 3.0.1 on 2020-05-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0032_auto_20200512_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherschedule',
            name='parent_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teacherschedule',
            name='student_name',
            field=models.CharField(max_length=200),
        ),
    ]
