# Generated by Django 3.0.1 on 2020-05-14 22:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0033_auto_20200512_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherschedule',
            old_name='busy_date_time',
            new_name='start_timestamp',
        ),
        migrations.AddField(
            model_name='teacherschedule',
            name='end_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 22, 36, 29, 840264)),
            preserve_default=False,
        ),
    ]
