# Generated by Django 3.0.1 on 2020-06-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_currencyexchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='role',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
