# Generated by Django 3.0.1 on 2020-05-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'permissions': (('view_current_module', 'Can view current module'), ('module_done', 'Module done'))},
        ),
    ]
