# Generated by Django 3.0.1 on 2020-06-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200617_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='1_MX40Njc2OTMyNH5-MTU5MjM4OTk5NTk2NH5WU0R4L0Y5ZThKWU1vdUUrV3VrMUpHTW9-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9MTViNjFmZWU5NTgyMGYyYzkxY2U0ZmZhZTBjODY0YWZlMmIyYjdiYjpzZXNzaW9uX2lkPTFfTVg0ME5qYzJPVE15Tkg1LU1UVTVNak00T1RrNU5UazJOSDVXVTBSNEwwWTVaVGhLV1UxdmRVVXJWM1ZyTVVwSFRXOS1VSDQmY3JlYXRlX3RpbWU9MTU5MjM4OTk5NiZleHBpcmVfdGltZT0xNTkyNDc2Mzk2JnJvbGU9cHVibGlzaGVyJm5vbmNlPTk5NjM0MyZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
