# Generated by Django 3.0.1 on 2020-06-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200617_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='1_MX40Njc2OTMyNH5-MTU5MjQwMTc4NzIyM341VmpsR1pkdTBpNmk1UGpZQklaMk9SY0J-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9M2EyMDBlNjU5ZGE5ZGE2M2Y2NmI3ZTE2Y2JlYzM1OTkwMjZlNTRhYzpzZXNzaW9uX2lkPTFfTVg0ME5qYzJPVE15Tkg1LU1UVTVNalF3TVRjNE56SXlNMzQxVm1wc1IxcGtkVEJwTm1rMVVHcFpRa2xhTWs5U1kwSi1VSDQmY3JlYXRlX3RpbWU9MTU5MjQwMTc4NyZleHBpcmVfdGltZT0xNTkyNDg4MTg3JnJvbGU9cHVibGlzaGVyJm5vbmNlPTIwMzM3OSZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
