# Generated by Django 3.0.1 on 2020-06-03 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_studentrewardcard_teacher'),
        ('courses', '0004_auto_20200602_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonroom',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.Schedule'),
        ),
    ]
