# Generated by Django 3.0.1 on 2020-06-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lessonroom_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='2_MX40Njc2OTMyNH5-MTU5MTI2OTQ1MzM4MH5ueG1wZ01pNU84QTJqMWRYTHhyVXpXUjN-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9ODRhMjVmMTIzOTJkN2YxZTM3MDQzMDZmMzg3ZGI2ZjFiZDFkOTcyNTpzZXNzaW9uX2lkPTJfTVg0ME5qYzJPVE15Tkg1LU1UVTVNVEkyT1RRMU16TTRNSDV1ZUcxd1owMXBOVTg0UVRKcU1XUllUSGh5VlhwWFVqTi1VSDQmY3JlYXRlX3RpbWU9MTU5MTI2OTQ1MyZleHBpcmVfdGltZT0xNTkxMzU1ODUzJnJvbGU9cHVibGlzaGVyJm5vbmNlPTM2NzMxMiZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
