# Generated by Django 3.0.1 on 2020-06-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200618_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='1_MX40Njc2OTMyNH5-MTU5MjQ3NTAzNzMzOH5qR0FEUHVNZ3RYUVVlaHFzejNjL3pHVyt-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9MmU5ZmJmOTg4ODEwZjU5NTg4Zjc5YzhkZDI4MzQ4ZjUwNDhjMjgzNzpzZXNzaW9uX2lkPTFfTVg0ME5qYzJPVE15Tkg1LU1UVTVNalEzTlRBek56TXpPSDVxUjBGRVVIVk5aM1JZVVZWbGFIRnplak5qTDNwSFZ5dC1VSDQmY3JlYXRlX3RpbWU9MTU5MjQ3NTAzNyZleHBpcmVfdGltZT0xNTkyNTYxNDM3JnJvbGU9cHVibGlzaGVyJm5vbmNlPTE3NTg5JmluaXRpYWxfbGF5b3V0X2NsYXNzX2xpc3Q9', max_length=400),
        ),
    ]
