# Generated by Django 3.0.1 on 2020-06-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200604_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='1_MX40Njc2OTMyNH5-MTU5MTM2MDE0NTUwNH5kTXR4TWx0L2ZieTVmTnJ0UUhLWkF4TzN-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9OGY3MDlkNTc4YTExOWFlZDgyODRkMWJlNTRjZDBjYmJjYzZhZjUyZTpzZXNzaW9uX2lkPTFfTVg0ME5qYzJPVE15Tkg1LU1UVTVNVE0yTURFME5UVXdOSDVrVFhSNFRXeDBMMlppZVRWbVRuSjBVVWhMV2tGNFR6Ti1VSDQmY3JlYXRlX3RpbWU9MTU5MTM2MDE0NSZleHBpcmVfdGltZT0xNTkxNDQ2NTQ1JnJvbGU9cHVibGlzaGVyJm5vbmNlPTU4ODk0MiZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
