# Generated by Django 3.0.1 on 2020-06-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200604_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='2_MX40Njc2OTMyNH5-MTU5MTM1NjMwMjEzM35kallKendqNFY5VEVyWW5nUCtSYXM1aUt-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9NGI1M2FkYzRhMjk1ODhlMmNiYTgwOTk4Yjc4MDZmMGEwN2FmZGMxNjpzZXNzaW9uX2lkPTJfTVg0ME5qYzJPVE15Tkg1LU1UVTVNVE0xTmpNd01qRXpNMzVrYWxsS2VuZHFORlk1VkVWeVdXNW5VQ3RTWVhNMWFVdC1VSDQmY3JlYXRlX3RpbWU9MTU5MTM1NjMwMiZleHBpcmVfdGltZT0xNTkxNDQyNzAyJnJvbGU9cHVibGlzaGVyJm5vbmNlPTQ2MDE2NCZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
