# Generated by Django 3.0.1 on 2020-06-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200605_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='1_MX40Njc2OTMyNH5-MTU5MTM2MTUxMjY4MH4wVFcxd3Q2eUhRbC9LVTF1TTZlczhkdTR-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9ZjQ0ZGFjNmRjNWQwYTEyYTUwMTU4NDE4NDQ2NDk2YjQzZDYwNzM4MzpzZXNzaW9uX2lkPTFfTVg0ME5qYzJPVE15Tkg1LU1UVTVNVE0yTVRVeE1qWTRNSDR3VkZjeGQzUTJlVWhSYkM5TFZURjFUVFpsY3poa2RUUi1VSDQmY3JlYXRlX3RpbWU9MTU5MTM2MTUxMiZleHBpcmVfdGltZT0xNTkxNDQ3OTEyJnJvbGU9cHVibGlzaGVyJm5vbmNlPTQ1NTA0OSZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
