# Generated by Django 3.0.1 on 2020-06-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200605_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='2_MX40Njc2OTMyNH5-MTU5MTQ1NjU1NjAzNn5VRlZteGNCUzRsaEtubFZidUtPaDJWd1h-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9NzNjYmQyM2QwOTg5NDE1YWZkZjg4MmI3MDBiZTY5ZTMzODQxOGE5YzpzZXNzaW9uX2lkPTJfTVg0ME5qYzJPVE15Tkg1LU1UVTVNVFExTmpVMU5qQXpObjVWUmxadGVHTkNVelJzYUV0dWJGWmlkVXRQYURKV2QxaC1VSDQmY3JlYXRlX3RpbWU9MTU5MTQ1NjU1NiZleHBpcmVfdGltZT0xNTkxNTQyOTU2JnJvbGU9cHVibGlzaGVyJm5vbmNlPTU3MTU4OSZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
