# Generated by Django 3.0.1 on 2020-06-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200618_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='1_MX40Njc2OTMyNH5-MTU5MjUxMTQ0NzY2MH5FOXhaNmFoZmFnbzFsL2tRdEljSlRDc1F-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9ZGM5MzQyZjEzMjVhYzExNWVkODRiZjdkYjU5NWE0Y2JhN2NmZDdjYzpzZXNzaW9uX2lkPTFfTVg0ME5qYzJPVE15Tkg1LU1UVTVNalV4TVRRME56WTJNSDVGT1hoYU5tRm9abUZuYnpGc0wydFJkRWxqU2xSRGMxRi1VSDQmY3JlYXRlX3RpbWU9MTU5MjUxMTQ0NyZleHBpcmVfdGltZT0xNTkyNTk3ODQ3JnJvbGU9cHVibGlzaGVyJm5vbmNlPTgxMDUxNSZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
