# Generated by Django 3.0.1 on 2020-04-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockly',
            name='answer',
            field=models.CharField(default='', max_length=300),
        ),
    ]
