# Generated by Django 3.0.1 on 2020-06-20 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20200618_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='1_MX40Njc2OTMyNH5-MTU5MjY4NTAxMjc0Nn5UemJrZWdqT0xYeWppdUN3aUdFaTZiUlV-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9MmQ4MjUxMmFlNjhkOTk4MjViZDI0M2I3NDZjZGFmZjdhOTNhMjBhNTpzZXNzaW9uX2lkPTFfTVg0ME5qYzJPVE15Tkg1LU1UVTVNalk0TlRBeE1qYzBObjVVZW1KclpXZHFUMHhZZVdwcGRVTjNhVWRGYVRaaVVsVi1VSDQmY3JlYXRlX3RpbWU9MTU5MjY4NTAxMiZleHBpcmVfdGltZT0xNTkyNzcxNDEyJnJvbGU9cHVibGlzaGVyJm5vbmNlPTIyNTc0NCZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=200)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial_subject', to='courses.Subject')),
            ],
        ),
    ]
