# Generated by Django 3.0.1 on 2020-06-05 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20200605_1229'),
        ('courses', '0008_auto_20200605_1251'),
    ]

    operations = [
    ]
