# Generated by Django 3.0.1 on 2020-06-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200606_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='1_MX40Njc2OTMyNH5-MTU5MTUzOTQzNzc2NH44dFNkQnRaRTgwZnM3TWFaNlJUYUJOY3R-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9NmUwNDkyMTAyM2M2ZTczMjhjZTViNTc5ZjdjNTg4MjFmMzI2ODIzZDpzZXNzaW9uX2lkPTFfTVg0ME5qYzJPVE15Tkg1LU1UVTVNVFV6T1RRek56YzJOSDQ0ZEZOa1FuUmFSVGd3Wm5NM1RXRmFObEpVWVVKT1kzUi1VSDQmY3JlYXRlX3RpbWU9MTU5MTUzOTQzNyZleHBpcmVfdGltZT0xNTkxNjI1ODM3JnJvbGU9cHVibGlzaGVyJm5vbmNlPTk5NjkyOCZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
