# Generated by Django 3.0.1 on 2020-06-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200620_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='2_MX40Njc2OTMyNH5-MTU5MjY4NTI4MTEwMH55eFkySlV4MHQyNXhaUTlSWjQxYjIrMWF-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9NGQyZTUyNzk1N2E4OThiMDgxNGY5OGJiZThmNGQ4ZjdhZmFkOTFjOTpzZXNzaW9uX2lkPTJfTVg0ME5qYzJPVE15Tkg1LU1UVTVNalk0TlRJNE1URXdNSDU1ZUZreVNsVjRNSFF5TlhoYVVUbFNXalF4WWpJck1XRi1VSDQmY3JlYXRlX3RpbWU9MTU5MjY4NTI4MSZleHBpcmVfdGltZT0xNTkyNzcxNjgxJnJvbGU9cHVibGlzaGVyJm5vbmNlPTUyNjc0JmluaXRpYWxfbGF5b3V0X2NsYXNzX2xpc3Q9', max_length=400),
        ),
    ]
