# Generated by Django 3.0.1 on 2020-06-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200607_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='1_MX40Njc2OTMyNH5-MTU5MTUzOTk4NTI4MH5RYmk5S1JBYmlsekcweDF3a2xTMEFoa0J-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9MzI2MjkxZjNiZDgzNTQ0NDRmMDIzNTYxZWUyZjM5ZDMzMDhjODBmNzpzZXNzaW9uX2lkPTFfTVg0ME5qYzJPVE15Tkg1LU1UVTVNVFV6T1RrNE5USTRNSDVSWW1rNVMxSkJZbWxzZWtjd2VERjNhMnhUTUVGb2EwSi1VSDQmY3JlYXRlX3RpbWU9MTU5MTUzOTk4NSZleHBpcmVfdGltZT0xNTkxNjI2Mzg1JnJvbGU9cHVibGlzaGVyJm5vbmNlPTc0MTgyMSZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
