# Generated by Django 3.0.1 on 2020-06-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20200620_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='2_MX40Njc2OTMyNH5-MTU5MjY4NTQyNjU4OH5hd2p2SFVSODBLQU5EYk1sbHhlUFFMakF-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9OTk1OTQ1NjAwNjBkNDU5ZGE4ZDkyZjc5ZDQ0M2Y1YjQ1NTNmNGM4ZTpzZXNzaW9uX2lkPTJfTVg0ME5qYzJPVE15Tkg1LU1UVTVNalk0TlRReU5qVTRPSDVoZDJwMlNGVlNPREJMUVU1RVlrMXNiSGhsVUZGTWFrRi1VSDQmY3JlYXRlX3RpbWU9MTU5MjY4NTQyNiZleHBpcmVfdGltZT0xNTkyNzcxODI2JnJvbGU9cHVibGlzaGVyJm5vbmNlPTc1MzI4MCZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
