# Generated by Django 3.0.1 on 2020-06-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20200607_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='2_MX40Njc2OTMyNH5-MTU5MTc4MzU2MzAzNn5wM1Y3QkI4UC9reHZqRW43aG1EQ2sxMit-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9MjExZWRiY2E3M2JmMzVlZTkzNjM1MDM5YTI0ZmU5MzNiOWVhZWI0ZTpzZXNzaW9uX2lkPTJfTVg0ME5qYzJPVE15Tkg1LU1UVTVNVGM0TXpVMk16QXpObjV3TTFZM1FrSTRVQzlyZUhacVJXNDNhRzFFUTJzeE1pdC1VSDQmY3JlYXRlX3RpbWU9MTU5MTc4MzU2MyZleHBpcmVfdGltZT0xNTkxODY5OTYzJnJvbGU9cHVibGlzaGVyJm5vbmNlPTU4MzU5NyZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
