# Generated by Django 3.0.1 on 2020-04-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_drag_and_drop'),
    ]

    operations = [
        migrations.AddField(
            model_name='drag_and_drop',
            name='answer1',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='drag_and_drop',
            name='answer2',
            field=models.CharField(default='', max_length=300),
        ),
    ]
