# Generated by Django 3.0.1 on 2020-04-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20200406_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drag_and_drop',
            old_name='answer1',
            new_name='answer_1',
        ),
        migrations.RenameField(
            model_name='drag_and_drop',
            old_name='answer2',
            new_name='answer_2',
        ),
        migrations.AddField(
            model_name='drag_and_drop',
            name='answer_correct',
            field=models.CharField(default='', max_length=300),
        ),
    ]
