# Generated by Django 3.0.1 on 2020-06-22 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20200620_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonroom',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='1_MX40Njc2OTMyNH5-MTU5MjgzOTI5MTcyM340R2ZhZjhDdnhWc0JZaDBSZ0RzYThhZWV-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9MGQ1ZDVlY2QyYzI5ODBhZDE2Mjc1ZDQyZWMxYzcxODY2N2I2YWY3ZDpzZXNzaW9uX2lkPTFfTVg0ME5qYzJPVE15Tkg1LU1UVTVNamd6T1RJNU1UY3lNMzQwUjJaaFpqaERkbmhXYzBKWmFEQlNaMFJ6WVRoaFpXVi1VSDQmY3JlYXRlX3RpbWU9MTU5MjgzOTI5MSZleHBpcmVfdGltZT0xNTkyOTI1NjkxJnJvbGU9cHVibGlzaGVyJm5vbmNlPTQxMTQ1NyZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
