# Generated by Django 3.0.1 on 2020-06-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_auto_20200610_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonroom',
            name='homework',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='2_MX40Njc2OTMyNH5-MTU5MTgwMjcwNzY1Nn5QM0h1RitSK0lVeG1pZnlrTUtOaXZzVWV-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9YmIyMTdmOGY4MTE5MDk4NDBmMDZiMmQyMTJhNTA5ZjU4ZDRkNTk4ZTpzZXNzaW9uX2lkPTJfTVg0ME5qYzJPVE15Tkg1LU1UVTVNVGd3TWpjd056WTFObjVRTTBoMVJpdFNLMGxWZUcxcFpubHJUVXRPYVhaelZXVi1VSDQmY3JlYXRlX3RpbWU9MTU5MTgwMjcwNyZleHBpcmVfdGltZT0xNTkxODg5MTA3JnJvbGU9cHVibGlzaGVyJm5vbmNlPTE4MTQ3NCZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
