# Generated by Django 3.0.1 on 2020-04-06 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20200406_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drag_and_drop',
            old_name='content',
            new_name='question',
        ),
    ]
