# Generated by Django 3.0.1 on 2020-06-23 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_teacher_manager'),
        ('courses', '0013_auto_20200622_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='1_MX40Njc2OTMyNH5-MTU5MjkzMjU5ODY1NX40M09ra1phdUxsUUV1ZXUvV1BGWkQ1cjh-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9NzhjNzMzOGRiNWY0NTU4NGIyZjhkZmRjZGU3M2Q3MjBhZTdjZWY4MDpzZXNzaW9uX2lkPTFfTVg0ME5qYzJPVE15Tkg1LU1UVTVNamt6TWpVNU9EWTFOWDQwTTA5cmExcGhkVXhzVVVWMVpYVXZWMUJHV2tRMWNqaC1VSDQmY3JlYXRlX3RpbWU9MTU5MjkzMjU5OCZleHBpcmVfdGltZT0xNTkzMDE4OTk4JnJvbGU9cHVibGlzaGVyJm5vbmNlPTUwMTQ1OCZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_amount', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('currency', models.CharField(choices=[('RUB', 'Ruble'), ('USD', 'Dollar'), ('EUR', 'Euro')], default='RUB', max_length=3)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
    ]
