# Generated by Django 3.0.1 on 2020-06-10 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20200610_1525'),
        ('courses', '0009_merge_20200605_1303'),
    ]

    operations = [
    ]
