# Generated by Django 3.0.1 on 2020-06-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20200610_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonroom',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='homework',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='1_MX40Njc2OTMyNH5-MTU5MTg2NzE2NjE3NX5CdDlzOW9oSkh3eDhLdHFSOWZZZXZ0UlV-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9NjJiMjNjYTUzZmUxNDFhNWZhMDgxZDYwOWM0OGQwOWIzNWIzZGM5NDpzZXNzaW9uX2lkPTFfTVg0ME5qYzJPVE15Tkg1LU1UVTVNVGcyTnpFMk5qRTNOWDVDZERsek9XOW9Ta2gzZURoTGRIRlNPV1paWlhaMFVsVi1VSDQmY3JlYXRlX3RpbWU9MTU5MTg2NzE2NiZleHBpcmVfdGltZT0xNTkxOTUzNTY2JnJvbGU9cHVibGlzaGVyJm5vbmNlPTk3OTA3NCZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
