# Generated by Django 3.0.1 on 2020-06-11 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20200611_0919'),
        ('courses', '0014_merge_20200610_1617'),
    ]

    operations = [
    ]
