# Generated by Django 3.0.1 on 2020-06-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20200623_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='2_MX40Njc2OTMyNH5-MTU5MjkzMzUxMzc4NH5KTDhRR0RGLzhQejRycEpNNFVpbEk4VlZ-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9MWYyNmQ0MjU1YzkxNzAyMjE4MjhkYzU5MjgxNmNjNjljNGQ5MzIzODpzZXNzaW9uX2lkPTJfTVg0ME5qYzJPVE15Tkg1LU1UVTVNamt6TXpVeE16YzROSDVLVERoUlIwUkdMemhRZWpSeWNFcE5ORlZwYkVrNFZsWi1VSDQmY3JlYXRlX3RpbWU9MTU5MjkzMzUxMyZleHBpcmVfdGltZT0xNTkzMDE5OTEzJnJvbGU9cHVibGlzaGVyJm5vbmNlPTI4OTIwNSZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
