# Generated by Django 3.0.1 on 2020-04-08 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20200406_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'permissions': (('assign_task', 'Assign task'),)},
        ),
    ]
