# Generated by Django 3.0.1 on 2020-06-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_merge_20200611_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='1_MX40Njc2OTMyNH5-MTU5MjA3NjAwMTUxN352cmxlVjFBSm1Ua1pFVk9JaFBkTUhjWXN-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9ZThjYWUxYWRhZWY1ZjQ0NGIyYTY5OGMwNTIzZjFkZTBkMzdiYWQwZDpzZXNzaW9uX2lkPTFfTVg0ME5qYzJPVE15Tkg1LU1UVTVNakEzTmpBd01UVXhOMzUyY214bFZqRkJTbTFVYTFwRlZrOUphRkJrVFVoaldYTi1VSDQmY3JlYXRlX3RpbWU9MTU5MjA3NjAwMSZleHBpcmVfdGltZT0xNTkyMTYyNDAxJnJvbGU9cHVibGlzaGVyJm5vbmNlPTkwNzM4NyZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
