# Generated by Django 3.0.1 on 2020-06-23 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_teacher_manager'),
        ('courses', '0015_auto_20200623_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='1_MX40Njc2OTMyNH5-MTU5MjkzMzY4ODU3MH5NNEVzdUZyYjZsUk1jYUpMUS9xb2RuYkJ-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9YjkyYzdjOTk5NjI5NjdhYzQzYjM5OWJlNjZlNTRmZWIzYTBhNTlkZjpzZXNzaW9uX2lkPTFfTVg0ME5qYzJPVE15Tkg1LU1UVTVNamt6TXpZNE9EVTNNSDVOTkVWemRVWnlZalpzVWsxallVcE1VUzl4YjJSdVlrSi1VSDQmY3JlYXRlX3RpbWU9MTU5MjkzMzY4OCZleHBpcmVfdGltZT0xNTkzMDIwMDg4JnJvbGU9cHVibGlzaGVyJm5vbmNlPTg0NTIyMyZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='students.Student'),
        ),
    ]
