# Generated by Django 3.0.1 on 2020-06-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20200613_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty_level',
            field=models.CharField(choices=[('BG', 'Beginner'), ('MD', 'Middle'), ('AD', 'Advanced')], default='BG', max_length=2),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images'),
        ),
        migrations.AddField(
            model_name='course',
            name='min_participant_age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='participant_level',
            field=models.CharField(choices=[('ST', 'Student'), ('TC', 'Teacher'), ('MN', 'Manager')], default='ST', max_length=2),
        ),
        migrations.AddField(
            model_name='course',
            name='repetition',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='1_MX40Njc2OTMyNH5-MTU5MjMwMDcyODE1OX5KK3pjcFdNa0NZb29QSUM0VkQ5cyt1MlB-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9MjliNzIxNmJmYjI1NWYwYmRjMzgyZTdmMTliZDMxODIxNzUzNGExODpzZXNzaW9uX2lkPTFfTVg0ME5qYzJPVE15Tkg1LU1UVTVNak13TURjeU9ERTFPWDVLSzNwamNGZE5hME5aYjI5UVNVTTBWa1E1Y3l0MU1sQi1VSDQmY3JlYXRlX3RpbWU9MTU5MjMwMDcyOCZleHBpcmVfdGltZT0xNTkyMzg3MTI4JnJvbGU9cHVibGlzaGVyJm5vbmNlPTM4NDAzMiZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=250, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
    ]
