# Generated by Django 3.0.1 on 2020-04-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20200408_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'permissions': (('assign_task', 'Assign task'),)},
        ),
    ]
