# Generated by Django 3.0.1 on 2020-06-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_auto_20200623_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='completed',
        ),
        migrations.AddField(
            model_name='subscription',
            name='past_lesson_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='2_MX40Njc2OTMyNH5-MTU5Mjk4OTk4MzE1NX5ncVdMRFpPSGE0WGZ1RTNsMGtZeEwxc1J-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9NjM2OTFkNjU4N2ZmOGIxOGU1MzZhMWIzOTVlZTI0MTUyMDIwODUwNDpzZXNzaW9uX2lkPTJfTVg0ME5qYzJPVE15Tkg1LU1UVTVNams0T1RrNE16RTFOWDVuY1ZkTVJGcFBTR0UwV0daMVJUTnNNR3RaZUV3eGMxSi1VSDQmY3JlYXRlX3RpbWU9MTU5Mjk4OTk4MyZleHBpcmVfdGltZT0xNTkzMDc2MzgzJnJvbGU9cHVibGlzaGVyJm5vbmNlPTYxNjMyMCZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
