# Generated by Django 3.0.1 on 2020-06-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20200616_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='1_MX40Njc2OTMyNH5-MTU5MjMwMTU2Mzg3Nn5iS0dvcktHS05lRUhUbHlTdkt1UzJwNFB-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9ZTVkZGQyNmZmNWMzZjk4MjQ1ZjY3MDY4Y2YxMTk2N2M5OGU0ZTExZDpzZXNzaW9uX2lkPTFfTVg0ME5qYzJPVE15Tkg1LU1UVTVNak13TVRVMk16ZzNObjVpUzBkdmNrdEhTMDVsUlVoVWJIbFRka3QxVXpKd05GQi1VSDQmY3JlYXRlX3RpbWU9MTU5MjMwMTU2MyZleHBpcmVfdGltZT0xNTkyMzg3OTYzJnJvbGU9cHVibGlzaGVyJm5vbmNlPTYxMzIxMyZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
