# Generated by Django 3.0.1 on 2020-06-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20200624_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='2_MX40Njc2OTMyNH5-MTU5Mjk5MzQ3MzUzN35iZGJnWWZONGJ3WStkVlg2bmZ1Ri91bm9-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9YmZlYmZiYTQ3NWNlZGZjNGFiNmNkNTI4ZDcyZTUxOGU2ZWFkMDljODpzZXNzaW9uX2lkPTJfTVg0ME5qYzJPVE15Tkg1LU1UVTVNams1TXpRM016VXpOMzVpWkdKbldXWk9OR0ozV1N0a1ZsZzJibVoxUmk5MWJtOS1VSDQmY3JlYXRlX3RpbWU9MTU5Mjk5MzQ3MyZleHBpcmVfdGltZT0xNTkzMDc5ODczJnJvbGU9cHVibGlzaGVyJm5vbmNlPTQzODU3NSZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
