# Generated by Django 3.0.1 on 2020-04-10 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20200410_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'permissions': (('assign_module', 'Assign module'),)},
        ),
    ]
