# Generated by Django 3.0.1 on 2020-06-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20200616_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_image',
        ),
        migrations.AddField(
            model_name='course',
            name='old_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='course',
            name='testimonial',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='testimonial_author',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='2_MX40Njc2OTMyNH5-MTU5MjMxMTM3MzQ1MX5xNEt0bkJhZ1h1RVBEQ1JOSVdkV2lmdVh-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9YTdhODkzMWY4ZjM1MTRhOTY4ODZlNThjYmVhZGFlMTYzZjM4ODBlODpzZXNzaW9uX2lkPTJfTVg0ME5qYzJPVE15Tkg1LU1UVTVNak14TVRNM016UTFNWDV4TkV0MGJrSmhaMWgxUlZCRVExSk9TVmRrVjJsbWRWaC1VSDQmY3JlYXRlX3RpbWU9MTU5MjMxMTM3MyZleHBpcmVfdGltZT0xNTkyMzk3NzczJnJvbGU9cHVibGlzaGVyJm5vbmNlPTMxNjYyNiZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
