# Generated by Django 3.0.1 on 2020-04-12 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20200410_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'permissions': (('view_current_module', 'Can view current module'),)},
        ),
    ]
