# Generated by Django 3.0.1 on 2020-06-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20200624_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='2_MX40Njc2OTMyNH5-MTU5MzE2NDQ4MzEzMX53UnlETGUvdDAyZFJwME1oSXM3UndpVm5-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9ZWMwMjBiODQ2YTYyMjM1ODM4M2FhOWNlOTFmYmRkZTY2MWZlODFjNjpzZXNzaW9uX2lkPTJfTVg0ME5qYzJPVE15Tkg1LU1UVTVNekUyTkRRNE16RXpNWDUzVW5sRVRHVXZkREF5WkZKd01FMW9TWE0zVW5kcFZtNS1VSDQmY3JlYXRlX3RpbWU9MTU5MzE2NDQ4MyZleHBpcmVfdGltZT0xNTkzMjUwODgzJnJvbGU9cHVibGlzaGVyJm5vbmNlPTczMTg0MSZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
