# Generated by Django 3.0.1 on 2020-06-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_auto_20200616_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='1_MX40Njc2OTMyNH5-MTU5MjMxNTkyODcyM35yK0pWY0FDbTI5dTM0c3FZaEthQnhkVmp-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9Y2QyMjc5MTcwM2RmNzFkMTE4MDQ0M2U5NjdlODU2OTU5ZWQ5ODM5MTpzZXNzaW9uX2lkPTFfTVg0ME5qYzJPVE15Tkg1LU1UVTVNak14TlRreU9EY3lNMzV5SzBwV1kwRkRiVEk1ZFRNMGMzRlphRXRoUW5oa1ZtcC1VSDQmY3JlYXRlX3RpbWU9MTU5MjMxNTkyOCZleHBpcmVfdGltZT0xNTkyNDAyMzI4JnJvbGU9cHVibGlzaGVyJm5vbmNlPTk3ODI0OCZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
