# Generated by Django 3.0.1 on 2020-06-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20200616_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='1_MX40Njc2OTMyNH5-MTU5MjMxMTUxOTAxM35aRVZ3RllVK3BBQVZhVEdDalBaeXRZRUp-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9NWM0ZTMyZWM3YmVlMDE0ODA5ZWQyMDg5NjkxZDliNWVlYjZkZTljZjpzZXNzaW9uX2lkPTFfTVg0ME5qYzJPVE15Tkg1LU1UVTVNak14TVRVeE9UQXhNMzVhUlZaM1JsbFZLM0JCUVZaaFZFZERhbEJhZVhSWlJVcC1VSDQmY3JlYXRlX3RpbWU9MTU5MjMxMTUxOSZleHBpcmVfdGltZT0xNTkyMzk3OTE5JnJvbGU9cHVibGlzaGVyJm5vbmNlPTI1MzkzNyZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
