# Generated by Django 3.0.1 on 2020-05-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20200412_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created'], 'permissions': (('course_done', 'Course done'),)},
        ),
    ]
