# Generated by Django 3.0.1 on 2020-06-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20200626_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='2_MX40Njc2OTMyNH5-MTU5MzE2NjEzMTA4Mn5RRFZrSWRYQ2JNTm92Q2lyMlBBMXVLY3p-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9MjhlYjA3NDJiZjJmYTI2MDgyMjViZmI5ZDVkNTUxZmVkZjIzZGJmYjpzZXNzaW9uX2lkPTJfTVg0ME5qYzJPVE15Tkg1LU1UVTVNekUyTmpFek1UQTRNbjVSUkZaclNXUllRMkpOVG05MlEybHlNbEJCTVhWTFkzcC1VSDQmY3JlYXRlX3RpbWU9MTU5MzE2NjEzMSZleHBpcmVfdGltZT0xNTkzMjUyNTMxJnJvbGU9cHVibGlzaGVyJm5vbmNlPTc3MzQzNCZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
