# Generated by Django 3.0.1 on 2020-06-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20200616_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='2_MX40Njc2OTMyNH5-MTU5MjMxNjkwMjg3OH4xNGloaDNDS1ZMM3pHSDFwL2hvdHRhamp-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9N2Y1OGE4YmRiNDNiYTE1NDYyYjkxYTJjMjAyNzRkYTg3ODdiZGUwMTpzZXNzaW9uX2lkPTJfTVg0ME5qYzJPVE15Tkg1LU1UVTVNak14Tmprd01qZzNPSDR4Tkdsb2FETkRTMVpNTTNwSFNERndMMmh2ZEhSaGFtcC1VSDQmY3JlYXRlX3RpbWU9MTU5MjMxNjkwMiZleHBpcmVfdGltZT0xNTkyNDAzMzAyJnJvbGU9cHVibGlzaGVyJm5vbmNlPTY2NTg0NyZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
