# Generated by Django 3.0.1 on 2020-06-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20200626_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='2_MX40Njc2OTMyNH5-MTU5MzI0NTkxMTUzMH4yZmRaN0h2c0xzNXNrc09nbVV6WEJTck1-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9MGE4MmE2OTIyMjVjZTNjNDY1N2QwYmE2NGExYjMwOTRhMzgwNjI3NzpzZXNzaW9uX2lkPTJfTVg0ME5qYzJPVE15Tkg1LU1UVTVNekkwTlRreE1UVXpNSDR5Wm1SYU4waDJjMHh6TlhOcmMwOW5iVlY2V0VKVGNrMS1VSDQmY3JlYXRlX3RpbWU9MTU5MzI0NTkxMSZleHBpcmVfdGltZT0xNTkzMzMyMzExJnJvbGU9cHVibGlzaGVyJm5vbmNlPTM0NTAyNyZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
