# Generated by Django 3.0.1 on 2020-06-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20200627_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='1_MX40Njc2OTMyNH5-MTU5MzI0NzA0NDczNX5zOE02Yy9RZDNDQ1VUVmh3eTkrMWh2U2F-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9ZmRmMjc1YmUxNjEyNzE2N2RkMzExYzFkMTE5NTc4MWNjN2JiYjVlNzpzZXNzaW9uX2lkPTFfTVg0ME5qYzJPVE15Tkg1LU1UVTVNekkwTnpBME5EY3pOWDV6T0UwMll5OVJaRE5EUTFWVVZtaDNlVGtyTVdoMlUyRi1VSDQmY3JlYXRlX3RpbWU9MTU5MzI0NzA0NCZleHBpcmVfdGltZT0xNTkzMzMzNDQ0JnJvbGU9cHVibGlzaGVyJm5vbmNlPTYxOTExMiZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
