# Generated by Django 3.0.1 on 2020-06-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_auto_20200627_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='1_MX40Njc2OTMyNH5-MTU5MzI0ODAyOTQxM35FRm5SZDZqTmtaTWxHMG93S2tiR1BibTJ-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9YTNjNTM0ODcyYjkyNDM2ZGQ3ZGZmYjAwNDg3OGFhMjQxYTI5MjY1YTpzZXNzaW9uX2lkPTFfTVg0ME5qYzJPVE15Tkg1LU1UVTVNekkwT0RBeU9UUXhNMzVGUm01U1pEWnFUbXRhVFd4SE1HOTNTMnRpUjFCaWJUSi1VSDQmY3JlYXRlX3RpbWU9MTU5MzI0ODAyOSZleHBpcmVfdGltZT0xNTkzMzM0NDI5JnJvbGU9cHVibGlzaGVyJm5vbmNlPTYzNjUmaW5pdGlhbF9sYXlvdXRfY2xhc3NfbGlzdD0=', max_length=400),
        ),
    ]
