# Generated by Django 3.0.1 on 2020-06-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_auto_20200627_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='2_MX40Njc2OTMyNH5-MTU5MzI0ODQwOTcyM35naHBrOE02SVJRZ3BLbHlrSS9sZVdCTy9-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9NDU3MGM4MTY2NmJmN2Q2Njg0ZWZlMGMwYTM1NmNkNzUwNGNlZTE1OTpzZXNzaW9uX2lkPTJfTVg0ME5qYzJPVE15Tkg1LU1UVTVNekkwT0RRd09UY3lNMzVuYUhCck9FMDJTVkpSWjNCTGJIbHJTUzlzWlZkQ1R5OS1VSDQmY3JlYXRlX3RpbWU9MTU5MzI0ODQwOSZleHBpcmVfdGltZT0xNTkzMzM0ODA5JnJvbGU9cHVibGlzaGVyJm5vbmNlPTY1NjU5NyZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
