# Generated by Django 3.0.1 on 2020-06-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_auto_20200627_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='1_MX40Njc2OTMyNH5-MTU5MzI0OTU0NjgwM35yQlRaUnFMb3JURkh5ZTFhRlJlZy81N0l-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9ZWI4Yzc1NmExNmY0ZGM4ZWY3NDI5OTYwYTcwNDIzNzgyNmY4NzI0MzpzZXNzaW9uX2lkPTFfTVg0ME5qYzJPVE15Tkg1LU1UVTVNekkwT1RVME5qZ3dNMzV5UWxSYVVuRk1iM0pVUmtoNVpURmhSbEpsWnk4MU4wbC1VSDQmY3JlYXRlX3RpbWU9MTU5MzI0OTU0NiZleHBpcmVfdGltZT0xNTkzMzM1OTQ2JnJvbGU9cHVibGlzaGVyJm5vbmNlPTYyODc5NCZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
