# Generated by Django 3.0.1 on 2020-06-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_auto_20200627_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='1_MX40Njc2OTMyNH5-MTU5MzI1MDk1ODQ3M35jZDMwY05UN0djMUt0WnVlOHNMWmlIT1Z-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9YTUwOWIyODhkNzc3ODQyNzU3NzQ3YTZhNjA5OGQ2ODdlYzMyZmIzMTpzZXNzaW9uX2lkPTFfTVg0ME5qYzJPVE15Tkg1LU1UVTVNekkxTURrMU9EUTNNMzVqWkRNd1kwNVVOMGRqTVV0MFduVmxPSE5NV21sSVQxWi1VSDQmY3JlYXRlX3RpbWU9MTU5MzI1MDk1OCZleHBpcmVfdGltZT0xNTkzMzM3MzU4JnJvbGU9cHVibGlzaGVyJm5vbmNlPTMyMTAzMiZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
