# Generated by Django 3.0.1 on 2020-06-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_auto_20200627_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='1_MX40Njc2OTMyNH5-MTU5MzQxNzY1MTM3Mn5nMzJ0OTVITUxaUmFWZ2J3aEx5dDBuOUl-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9YmNmZDRiZjhkOGMwZmQ1N2QzZjk2NGNiMmFhYjNlMzY4NDllNDQwYTpzZXNzaW9uX2lkPTFfTVg0ME5qYzJPVE15Tkg1LU1UVTVNelF4TnpZMU1UTTNNbjVuTXpKME9UVklUVXhhVW1GV1oySjNhRXg1ZERCdU9VbC1VSDQmY3JlYXRlX3RpbWU9MTU5MzQxNzY1MSZleHBpcmVfdGltZT0xNTkzNTA0MDUxJnJvbGU9cHVibGlzaGVyJm5vbmNlPTY4Mzg1MSZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
