# Generated by Django 3.0.1 on 2020-06-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_auto_20200629_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='1_MX40Njc2OTMyNH5-MTU5MzQxODYzNzQ1NH41VkRuWnFNU0xvV1NwMjJVM2tobEdsOUJ-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9ZTM5MzNmZDZjM2NiMjNlNWNjOGM4MjJlZmQ4YTAwZjg2YjMyYTNkZDpzZXNzaW9uX2lkPTFfTVg0ME5qYzJPVE15Tkg1LU1UVTVNelF4T0RZek56UTFOSDQxVmtSdVduRk5VMHh2VjFOd01qSlZNMnRvYkVkc09VSi1VSDQmY3JlYXRlX3RpbWU9MTU5MzQxODYzNyZleHBpcmVfdGltZT0xNTkzNTA1MDM3JnJvbGU9cHVibGlzaGVyJm5vbmNlPTcyNDIyNyZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
