# Generated by Django 3.0.1 on 2020-06-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_auto_20200629_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonroom',
            name='session_id',
            field=models.CharField(default='1_MX40Njc2OTMyNH5-MTU5MzQxOTE2MTYzM354dC9rZ0pCdmM5a3VJUVFoUVhraHpHOGR-UH4', max_length=100),
        ),
        migrations.AlterField(
            model_name='lessonroom',
            name='token',
            field=models.CharField(default='T1==cGFydG5lcl9pZD00Njc2OTMyNCZzaWc9YmE2NjliZTA5ZGFkYTUwNjk2YmJiMzI0MDAyYjE4NzU3YzA4ZDg3MTpzZXNzaW9uX2lkPTFfTVg0ME5qYzJPVE15Tkg1LU1UVTVNelF4T1RFMk1UWXpNMzU0ZEM5clowcENkbU01YTNWSlVWRm9VVmhyYUhwSE9HUi1VSDQmY3JlYXRlX3RpbWU9MTU5MzQxOTE2MSZleHBpcmVfdGltZT0xNTkzNTA1NTYxJnJvbGU9cHVibGlzaGVyJm5vbmNlPTU3MDAzMCZpbml0aWFsX2xheW91dF9jbGFzc19saXN0PQ==', max_length=400),
        ),
    ]
